Config.Language = {
    -- Shop name
    fishingShop = "Fishing_Shop",

    -- Notifications
    canceled = "Canceled",
    wrongBait = "The bait cannot be used here.",
    wrongZone = "You are not in a fishing zone.",
    gotFishFishingnet = "You got some fish on your fishing net! Go collect it!",
    fishingnetSpawned = "You have already spawned a fishing net.",
    fishingnetWrongZone = "You are not in a fishing net zone.",
    upgradeSucess = "Upgrade successful:",
    noMaterials = "You do not have the necessary materials.",
    youCaught = "You caught a",
    youSold = "You sold:",
    youReceive = "and you received:",
    noItems = "You don't have the required items.",
    noFishbait = "You don't have any fishbait.",
    noFishnet = "You don't have any fishnet.",
    noIllegalZone = "You are not in an illegal fishing zone.",
    youEarn = "You earned +",
    experience = "experience!",
    suitOut = "You took off your diving suit",
    oxyEnd = "Oxygen is finished!",
    oxyFull = "Full oxygen tube!",
    refillWrong = "You cannot fill an already used tank",
    suitWrong = "You need to be out of the water/car to put on your wetsuit",
    noTube = "You need an oxygen tube",
    foundSomething = "Looks like you found something!",
    sameLocation = "This place has already been searched!",
    minigameFailed = "You failed the minigame!",
    noLicense = "You dont have fishing license, go get one!",
    getLicense = "You get a fishing license!",
    youGotLicense = "You already have fishing license.",
    anchorStuck = "The anchor is stuck on the ground!",
    anchorPulled = "The anchor has been pulled!",
    notStarted = "The tournament hasn't started yet!",
    noFishingKey = "You dont have the fishing key",
    youFound = "You found:",
    nothingInside = "You didn't find anything inside",
    noKnife = "You dont have a knife to cut the tigershark",
    tournamentName = "Tournament Name:",
    timeClosing = "Time until closing:",
    minutes = "minute(s)",
    minutesJoin = "minute(s)<br>[E] - Join Tournament",
    time = "Time:",
    seconds = "second(s)",
    yourXp = "Your fishing XP:",
    noXp = "You have no fishing XP.",
    noMoney = "You dont have enought money",
    noPolice = "Not enough police online to fish illegally",
    swimming = "You can't use fishingnet while swimming",

    -- Progressbars
    progGetFish = "Trying to get some fish...",
    progIllegalBait = "Making illegal bait...",
    progCollectShell = "Collecting shell...",
    progFishingnet = "Placing fishing net...",
    progCollectFishingnet = "Collecting fishing net...",
    progCollectCoral = "Collecting coral...",
    progVestSuit = "Wear a diving suit..",
    progOutSuit = "Remove diving suit..",
    progPlacingBonfire = "Placing bonfire...",
    progSaveBonfire = "Saving bonfire...",
    progPulAnchor = "Pulling anchor...",
    progDropAnchor = "Dropping anchor...",
    progOpenTreasure = "Opening treasure chest...",

    -- Targets
    tarFishingShop = "Fishing Shop",
    tarGetLicese = "Get License",
    tarUpgrades = "Upgrade Fishingrod / Fishingnet",
    tarCollectShell = "Collect Shell",
    tarSellFish = "Sell Fish",
    tarSellIllegalFish = "Sell Illegal Fish",
    tarSellSeashell = "Sell Seashell",
    tarCollectFishingnet = "Collect fishing net",
    tarRentBoat = "Rent Boat",
    tarCollectCoral = "Collect Coral",
    tarCooking = "Cooking",
    tarSaveBonfire = "Save Bonfire",
    tarSellCorals = "Sell Corals",
    tarJoinTournament = "Join Tournament",

    -- Help Text
    helpFishingShop = "[E] - Open Shop<br>[F] - Open Upgrade Menu",
    helpFishingShopLicense = "[E] - Open Shop<br>[F] - Open Upgrade Menu<br>[H] - Get License",
    helpCollectShell = "[E] - Collect Shell",
    helpSellFish = "[E] - Sell Fish",
    helpSellIllegalFish = "[E] - Sell Illegal Fish",
    helpCollectFishingnet = "[E] - Collect Fishing net",
    helpDeleteVehicle = "[E] - Delete Vehicle",
    helpCollectCoral = "[E] - Collect Coral",
    timeFishingnet = "Time:",
    secondsFishingnet = "seconds",
    helpCooking = "[E] - Cooking<br>[F] - Saving Bonfire",
    helpSellCorals = "[E] - Sell Corals",
    helpJoinTournament = "[E] - Join Tournament",
    placeBonfire = "[E] - Place Bonfire   \n[Q] - Cancel  \n[Mouse Scroll] - Rotate",

    -- Menus
    currency = "$",
    headerBoat = "Rent Boat",
    boat = "Boat:",
    xpNeeded = "Experience necessary:",
    headerUpgrades = "Upgrade Menu",
    requiredItems = "Necessary Items:"
}
