Crafting = Crafting or {}

Crafting.ChoppingBoard = {
    Header = locale("menu", "food"),
    Anims = CraftingEmotes.Typing,
    progressBar = { label = locale("progressbar", "progress_make"), time = 5000, },
    Recipes = {
        { bmochi = { sugar = 1, flour = 1, blueberry = 1, },
            ["amount"] = 1,
        },
        { gmochi = { sugar = 1, flour = 1, mint = 1, },
            ["amount"] = 1,
        },
        { omochi = { sugar = 1, flour = 1, orange = 1, },
            ["amount"] = 1,
        },
        { pmochi = { sugar = 1, flour = 1, strawberry = 1, },
            ["amount"] = 1,
        },
        { riceball = { rice = 1, nori = 1, },
            ["amount"] = 1,
        },
        { bento = { rice = 1, nori = 1, tofu = 1, },
            ["amount"] = 1,
        },
        { purrito = { rice = 1, flour = 1, onion = 1, },
            ["amount"] = 1,
        },
    }
}

Crafting.Oven = {
    Header = locale("menu", "oven"),
    Anims = CraftingEmotes.Oven,
    progressBar = { label = locale("progressbar", "progress_make"), time = 5000, },
    Recipes = {
        { nekocookie = { flour = 1, milk = 1, },
            ["amount"] = 1,
        },
        { nekodonut = { flour = 1, milk = 1, },
            ["amount"] = 1,
        },
        { cake = { flour = 1, milk = 1, strawberry = 1, },
            ["amount"] = 1,
        },
        { cakepop = { flour = 1, milk = 1, sugar = 1, },
            ["amount"] = 1,
        },
        { pancake = { flour = 1, milk = 1, strawberry = 1, },
            ["amount"] = 1,
        },
        { pizza = { flour = 1, milk = 1,},
            ["amount"] = 1,
        },
    },
}

Crafting.Coffee = {
    Header = locale("menu", "coffee"),
    Anims = CraftingEmotes.Pour,
    progressBar = { label = locale("progressbar", "progress_pour"), time = 5000, },
    Recipes = {
        { catcoffee = { },
            ["amount"] = 1,
        },
        { nekolatte = { },
            ["amount"] = 1,
        },
        { bobatea = { boba = 1, milk = 1,},
            ["amount"] = 1,
        },
        { bbobatea = { boba = 1, milk = 1, sugar = 1,},
            ["amount"] = 1,
        },
        { gbobatea = { boba = 1, milk = 1, strawberry = 1, },
            ["amount"] = 1,
        },
        { obobatea = { boba = 1, milk = 1, orange = 1,},
            ["amount"] = 1,
        },
        { pbobatea = { boba = 1, milk = 1, strawberry = 1,},
            ["amount"] = 1,
        },
        { mocha = { milk = 1, sugar = 1,},
            ["amount"] = 1,
        },
    },
}

Crafting.Hob = {
    Header = locale("menu", "hob"),
    Anims = CraftingEmotes.Grill,
    progressBar = { label = locale("progressbar", "progress_make"), time = 5000, },
    Recipes = {
        { miso = { nori = 1, tofu = 1, onion = 1, },
            ["amount"] = 1,
        },
        { ramen = { noodles = 1, onion = 1, },
            ["amount"] = 1,
        },
        { noodlebowl = { noodles = 1, },
            ["amount"] = 1,
        },
    }
}