-- --Items


-- -- OX INVENTORY

-- ['spanner'] = {
--     label = 'Spanner',
--     weight = 1000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['firelighter'] = {
--     label = 'Firelighters',
--     weight = 500,
--     stack = false,
--     close = true,
--     description = nil
-- },
-- ['adjustable_spanner'] = {
--     label = 'Spanner',
--     weight = 1000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['drill'] = {
--     label = 'Drill',
--     weight = 3000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['buzz_saw'] = {
--     label = 'Buzz Saw',
--     weight = 6000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['impact_driver'] = {
--     label = 'Impact Driver',
--     weight = 4000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['pliers'] = {
--     label = 'Pliers',
--     weight = 1000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['impact_bomb'] = {
--     label = 'Impact Explosive',
--     weight = 3000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['ignition_bomb'] = {
--     label = 'Ignition Explosive',
--     weight = 3000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['remote_bomb'] = {
--     label = 'Remote Explosive',
--     weight = 3000,
--     stack = true,
--     close = true,
--     description = nil
-- },
-- ['phone_bomb'] = {
--     label = 'Detonator Device',
--     weight = 1000,
--     stack = false,
--     close = true,
--     description = nil
-- },
-- ['speed_bomb'] = {
--     label = 'Speed Bomb',
--     weight = 1000,
--     stack = false,
--     close = true,
--     description = nil
-- },
-- ['screwdriver'] = {
--     label = 'Screwdriver',
--     weight = 1000,
--     stack = false,
--     close = true,
--     description = nil
-- },


-- -- QB INVENTORY
-- ['speed_bomb']                        = {['name'] = 'speed_bomb',                     ['label'] = 'Speed Bomb',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'speed_bomb.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['screwdriver']                        = {['name'] = 'screwdriver',                     ['label'] = 'Screwdriver',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'screwdriver.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['phone_bomb']                        = {['name'] = 'phone_bomb',                     ['label'] = 'Detonator Device',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'impact_bomb.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['remote_bomb']                   = {['name'] = 'remote_bomb',                     ['label'] = 'Remote Explosive',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'impact_bomb.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['ignition_bomb']                   = {['name'] = 'ignition_bomb',                 ['label'] = 'Ignition Explosive',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'ignition_bomb.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['impact_bomb']                   = {['name'] = 'impact_bomb',                     ['label'] = 'Impact Explosive',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'impact_bomb.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['firelighter']                   = {['name'] = 'firelighter',                     ['label'] = 'Fire Lighters',                             ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'firelighter.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['impact_driver']                   = {['name'] = 'impact_driver',                 ['label'] = 'Impact Driver',                             ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'impact_driver.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['buzz_saw']                       = {['name'] = 'buzz_saw',                         ['label'] = 'Buzz Saw',                                 ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'buzz_saw.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['spanner']                       = {['name'] = 'spanner',                         ['label'] = 'Spanner',                                     ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'spanner.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},
-- ['adjustable_spanner']              = {['name'] = 'adjustable_spanner',             ['label'] = 'Adjustable Spanner',                         ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'adjustable_spanner.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] =nil},
-- ['pliers']                           = {['name'] = 'pliers',                         ['label'] = 'Pliers',                                     ['weight'] = 500,         ['type'] = 'item',         ['image'] = 'pliers.png',                 ['unique'] = true,         ['useable'] = true,     ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = nil},